# Generated by Django 2.2.5 on 2019-10-15 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmtable',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
            preserve_default=False,
        ),
    ]
